[package]
name = "sunbeam"
version = "2.0.0-rc4"
edition = "2024"
license = "MIT"
repository = "https://src.sunbeam.pt/studio/cli"
description = "Sunbeam Studios CLI"

[[bin]]
name = "sunbeam"
path = "src/main.rs"

[dependencies]
sunbeam-sdk.workspace = true
tokio = { workspace = true }
tracing.workspace = true
tracing-subscriber.workspace = true
rustls.workspace = true
